### ISSUE TITLE
Hashrate shows "waiting..." after start

### ISSUE THREAD

**Issue by bcFenix** [jwinterm/monerospelunker#6]
Hello,

I have spelunker running on 4 windows machines.  1 is Windows 10, the other 3 are Windows Server 2012R2.  The hashrate "waiting..." is present on 2 of my server 2012R2 machines, even though I've started mining and the miner output is outputting.  I can't think of any differences between my 2 trouble Server 2012R2 machines and the one good one.  Any insight to this? 
Thanks

**Comment by bcFenix** [comment]
![image](https://user-images.githubusercontent.com/35649017/35191237-ddc7abe2-fe43-11e7-8948-d147078f2d4d.png)

**Comment by jwinterm** [comment]
Your hashrate is so low (1 h/s) that you never find a share, would be my best guess. Normal share diffs are 10k, so it would take you several hours to find a share probably.

**Comment by bcFenix** [comment]
Hello,
Thanks for replying.  I don't think this is the case.  These machines are very similar in specs and I've verified their hashrates using minergate and looking on my elected pool's website.  I wanted to switch away from minergate and to another miner that has GUI along with thread control.  Any other insight you could provide me as to why the hashrate won't show up?

**Comment by jwinterm** [comment]
It shows the hashrate in the picture you attached. It says 1.03 h/s. You
can try running the CPU miner without GUI and see what you get.

**Comment by bcFenix** [comment]
Hello,
The miner ouput only shows 1 line and I'm unable to expand it.  Here's the output from minerd

![image](https://user-images.githubusercontent.com/35649017/35342032-0c15674c-00f5-11e8-8de9-cd2a289c3c7e.png)

**Comment by jwinterm** [comment]
I don't know. If you're getting shares with the CLI program I'd just use
that.

**Comment by bcFenix** [comment]
Ok, thank you for your input.  I am still getting shares using the GUI, according to the pool's site.  Just wanted to see what I was missing in order to get the hashrate to display.
